---

name: Build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the tag version
        id: get_tag
        run: |
          echo ::set-output name=tag::${GITHUB_SHA}

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...

      - name: Test Race
        run: go test -cpu=2 -race ./...

      - name: Build
        run: |
          VERSION=${{ steps.get_tag.outputs.tag }} ./build.sh
